import {test} from 'node:test';
import assert from 'node:assert/strict';
import {calculate,calculateMercadoLivre,calculateShopee,calculateTikTokShop,calculateMargin,calculateMarkup,calculateProfit,calculateTargetPrice,calculateBreakEven,calculateKit,compareMarketplaces,calculateMonthlyProjection,calculateFullStorage,calculateBillableWeight,cents,percentage,validateRule} from '../calculations/index';
import {defaultSale,defaultContexts,emptyRule,defaultRules,markets} from './demoFees';
import type {Rule} from '../types/index';
const s={...defaultSale,price:4999,cost:1800,packaging:150};
const c=defaultContexts;
for(const m of markets){for(const price of [1,100,500,999,1249,1250,1999,2999,4999,5000,7899,7900,7901,7999,9999,10000,12990,19990,50000,100000,1000000,10000000])test(`${m}: preço ${price} centavos`,()=>{const r=calculate({...s,price},m,c[m],defaultRules);assert.equal(r.gross,price);assert.equal(r.profit,r.revenue-r.lines.reduce((a,l)=>a+l.value,0));assert.ok(Number.isSafeInteger(r.fees));});}
test('motores separados e taxas detalhadas',()=>{assert.equal(calculateMercadoLivre(s,c.ml,defaultRules).lines[0].value,600);assert.equal(calculateShopee(s,c.shopee,defaultRules).lines[0].value,700);assert.equal(calculateTikTokShop(s,c.tiktok,defaultRules).lines[0].value,500);});
test('lucro, margem e markup',()=>{assert.equal(calculateProfit(10000,6000),4000);assert.equal(calculateMargin(4000,10000),40);assert.equal(calculateMarkup(9000,6000),50);assert.equal(calculateMarkup(10000,0),null);});
test('arredondamento inteiro e leitura decimal',()=>{assert.equal(cents('49,99'),4999);assert.equal(cents('100000.00'),10000000);assert.equal(percentage(5,10),1);assert.equal(percentage(4999,6),300);assert.throws(()=>cents('1.001'));assert.throws(()=>cents('NaN'));});
test('faixas TikTok inclusivas e sem sobreposição',()=>{assert.equal(calculate({...s,price:4999},'tiktok',c.tiktok,defaultRules).fees,900);assert.equal(calculate({...s,price:5000},'tiktok',c.tiktok,defaultRules).fees,900);});
test('quantidade, fixa por pedido e taxa por item',()=>{const r=calculate({...s,price:10000,quantity:3},'ml',{...c.ml,manual:true,percentage:10,fixed:100,perUnit:200},[]);assert.equal(r.fees,3700);assert.equal(r.lines.find(l=>l.name==='Custo do produto')?.value,5400);});
test('opcionais zero, descontos e afiliado',()=>{const r=calculate({...s,price:10000,discount:1000,tax:10},'shopee',{...c.shopee,manual:true,percentage:10,fixed:0,perUnit:0,affiliate:5,logisticRate:5,campaign:5},[]);assert.equal(r.fees,2250);assert.equal(r.netRevenue,5850);});
test('validar entradas negativas, NaN, Infinity, quantidade e percentuais',()=>{for(const patch of [{price:0},{price:-1},{cost:-1},{quantity:0},{quantity:1.5},{price:Infinity},{cost:NaN},{tax:101},{tax:-2},{discount:4999}])assert.throws(()=>calculate({...s,...patch},'ml',c.ml,defaultRules));assert.throws(()=>validateRule({...emptyRule,min:5000,max:4999}));});
for(const m of markets)test(`${m}: preço ideal e equilíbrio mínimos, comparados com busca exaustiva`,()=>{const ss={...s,cost:200,packaging:50};for(const target of [0,10,30]){const actual=calculateTargetPrice(ss,m,c[m],defaultRules,target);let expected:number|null=null;for(let p=1;p<20000;p++){const r=calculate({...ss,price:p},m,c[m],defaultRules);if(BigInt(r.profit)*BigInt(10000)>=BigInt(r.revenue)*BigInt(target*100)){expected=p;break;}}assert.equal(actual,expected);}assert.equal(calculateBreakEven(ss,m,c[m],defaultRules),calculateTargetPrice(ss,m,c[m],defaultRules,0));});
test('preço ideal encontra queda de tarifa e ignora lacuna sem regra',()=>{const rules:Rule[]=[{...emptyRule,id:'a',market:'ml',percentage:99,min:1,max:4999},{...emptyRule,id:'b',market:'ml',percentage:5,min:5000,max:null}];assert.equal(calculateBreakEven({...s,cost:1000,packaging:0},'ml',c.ml,rules),5000);assert.equal(calculateBreakEven({...s,cost:1,packaging:0},'ml',c.ml,[rules[1]]),5000);});
test('vigência, categoria, inatividade e anúncio filtram regras',()=>{const rules:Rule[]=[{...emptyRule,id:'active',market:'ml',percentage:10,category:'Pesca',start:'2026-10-01',end:'2026-10-30',listing:'Premium'},{...emptyRule,id:'off',percentage:90,active:false}];assert.equal(calculate(s,'ml',{...c.ml,category:'Pesca',listing:'Premium'},rules).fees,500);assert.equal(calculate(s,'ml',c.ml,rules).warnings.length,1);});
test('sem solução e taxa de 100%',()=>{assert.equal(calculateTargetPrice(s,'ml',{...c.ml,manual:true,percentage:100},[],30),null);assert.equal(calculateTargetPrice(s,'ml',c.ml,defaultRules,100),null);});
test('arredondamento não monotônico ainda encontra mínimo exato',()=>{const cc={...c.shopee,manual:true,percentage:33.33,affiliate:33.33,logisticRate:33.33,campaign:0};const ss={...s,cost:1,packaging:0};let expected:number|null=null;for(let p=1;p<20000;p++){if(calculate({...ss,price:p},'shopee',cc,[]).profit>=0){expected=p;break;}}assert.equal(calculateBreakEven(ss,'shopee',cc,[]),expected);});
test('kits: um item anunciado com múltiplas unidades internas',()=>{const k=calculateKit(s,'ml',c.ml,defaultRules,6,24990);assert.equal(k.lines.find(l=>l.name==='Custo do produto')?.value,10800);assert.equal(k.lines.find(l=>l.name.includes('por item'))?.value,600);assert.equal(k.unitProfit,k.profit/6);assert.equal(k.unitMargin,k.margin);});
test('comparação e projeção mensal',()=>{const rows=compareMarketplaces(s,c,defaultRules);assert.equal(rows.length,3);const r=calculate(s,'ml',c.ml,defaultRules);const p=calculateMonthlyProjection(r,100);assert.equal(p.profit,r.profit*100);assert.equal(p.fees,r.fees*100);assert.equal(p.margin,r.margin);assert.equal(calculateMonthlyProjection(r,0).gross,0);});
test('Mercado Livre Full: armazenagem diária por porte e peso faturável',()=>{assert.equal(calculateFullStorage({...c.ml,logistics:'Full',fullSize:'Pequeno',fullDays:30},1),21);assert.equal(calculateFullStorage({...c.ml,logistics:'Full',fullSize:'Médio',fullDays:30},1),45);assert.equal(calculateFullStorage({...c.ml,logistics:'Full',fullSize:'Grande',fullDays:30},1),150);assert.equal(calculateFullStorage({...c.ml,logistics:'Full',fullSize:'Extragrande',fullDays:30},1),321);assert.equal(calculateBillableWeight({...c.ml,weightKg:2.5,heightCm:30,widthCm:30,lengthCm:25}),4.5);});
test('Mercado Livre Full: inclui armazenagem, Ads, ROI e alerta de R$79',()=>{const cc={...c.ml,manual:true,percentage:12,logistics:'Full',fullSize:'Pequeno' as const,fullDays:30};const r=calculate({...s,price:7900,cost:2000,shipping:800,ads:5},'ml',cc,[]);assert.equal(r.lines.find(l=>l.name==='Armazenagem Full')?.value,21);assert.equal(r.lines.find(l=>l.name==='Publicidade / Ads')?.value,395);assert.ok(r.roi!==null);assert.ok(r.warnings.some(w=>w.includes('R$ 79')));});
test('Mercado Livre Full: preço ideal considera Ads e armazenagem',()=>{const cc={...c.ml,manual:true,percentage:12,logistics:'Full',fullSize:'Pequeno' as const,fullDays:30};const ss={...s,cost:2000,ads:5};const p=calculateTargetPrice(ss,'ml',cc,[],30);assert.ok(p!==null);const current=calculate({...ss,price:p!},'ml',cc,[]);assert.ok(current.margin>=30);if(p!>1)assert.ok(calculate({...ss,price:p!-1},'ml',cc,[]).margin<30);});
test('preço alto sem teto comercial e ponto de equilíbrio',()=>{const ss={...s,cost:10000000};const price=calculateTargetPrice(ss,'ml',c.ml,defaultRules,30);assert.ok(price!==null&&price>10000000);const r=calculate({...ss,price:price!},'ml',c.ml,defaultRules);assert.ok(r.margin>=30);assert.ok(calculate({...ss,price:price!-1},'ml',c.ml,defaultRules).margin<30);});

import {defaultRules as officialRules, defaultContexts as currentContexts} from '../config/marketplaceFees';
import {reconcileRules} from '../storage/feeMigration';
test('TikTok oficial: mudança de faixa usa preço após desconto do vendedor',()=>{const r=calculate({...s,price:6000,discount:1001},'tiktok',{...currentContexts.tiktok,logisticRate:0},officialRules);assert.equal(r.fees,900);assert.equal(r.lines[0].value,500);assert.equal(r.lines[2].value,400);});
test('TikTok oficial: fronteira exata em R$50 líquidos',()=>{const r=calculate({...s,price:6000,discount:1000},'tiktok',{...currentContexts.tiktok,logisticRate:0},officialRules);assert.equal(r.lines[0].value,300);assert.equal(r.lines[2].value,600);});
test('TikTok SFP: teto de R$50 por item para múltiplos itens',()=>{const r=calculate({...s,price:100000,quantity:3},'tiktok',currentContexts.tiktok,officialRules);assert.equal(r.lines.find(l=>l.name==='Programa logístico')?.value,15000);});
test('TikTok SFP: 6% abaixo do teto',()=>{const r=calculate({...s,price:47000},'tiktok',currentContexts.tiktok,officialRules);assert.equal(r.lines.find(l=>l.name==='Programa logístico')?.value,2820);});
test('Preço ideal respeita faixa líquida e teto SFP',()=>{for(const cost of [2000,60000,100000]){const ss={...s,cost,discount:1000};const p=calculateTargetPrice(ss,'tiktok',currentContexts.tiktok,officialRules,30);assert.ok(p!==null);const result=calculate({...ss,price:p!},'tiktok',currentContexts.tiktok,officialRules);assert.ok(BigInt(result.profit)*BigInt(10000)>=BigInt(result.revenue)*BigInt(3000));const previous=calculate({...ss,price:p!-1},'tiktok',currentContexts.tiktok,officialRules);assert.ok(BigInt(previous.profit)*BigInt(10000)<BigInt(previous.revenue)*BigInt(3000));}});
test('Regra oficial não é aplicada antes da vigência',()=>{const r=calculate({...s,date:'2026-07-14'},'tiktok',currentContexts.tiktok,officialRules);assert.equal(r.warnings.length,1);});
test('Migração remove demonstrações e preserva personalizações',()=>{const custom={...defaultRules[0],percentage:13};const migrated=reconcileRules([...defaultRules,custom]);assert.equal(migrated.length,officialRules.length+1);assert.equal(migrated.filter(r=>r.origin==='official').length,officialRules.length);assert.ok(migrated.some(r=>r.percentage===13));});
test('Não há tabela universal fictícia de ML',()=>{assert.equal(officialRules.some(r=>r.market==='ml'),false);});

const sc={...currentContexts.shopee,logisticRate:6};
for(const [price,expected] of [[1,1],[500,350],[899,630],[900,630],[4999,1450],[7999,2050],[8000,2720],[9999,3000],[10000,3400],[19999,4800],[20000,5400],[50000,9600],[100000,16600]])
 test('Shopee oficial CNPJ: '+price+' centavos',()=>{const r=calculate({...s,price},'shopee',sc,officialRules);assert.equal(r.fees,expected);assert.equal(r.warnings.length,0);});
test('Shopee: metade por item arredondada individualmente e quantidade',()=>{assert.equal(calculate({...s,price:899,quantity:3},'shopee',sc,officialRules).fees,1889);});
test('Shopee: faixa considera desconto do vendedor',()=>{assert.equal(calculate({...s,price:8500,discount:501},'shopee',sc,officialRules).fees,2050);});
test('Shopee CPF: adicional somente acima de 450 pedidos em 90 dias',()=>{for(const orders90 of [0,450,451])assert.equal(calculate({...s,price:8000},'shopee',{...sc,seller:'Pessoa Física',orders90},officialRules).fees,orders90>450?3020:2720);});
test('Shopee CPF: tarifa regressiva não publicada impede resultado confiável',()=>{const cc={...sc,seller:'Pessoa Física',orders90:451};assert.equal(calculate({...s,price:1199},'shopee',cc,officialRules).warnings.length,1);assert.equal(calculate({...s,price:1200},'shopee',cc,officialRules).fees,990);assert.throws(()=>calculateTargetPrice(s,'shopee',cc,officialRules,30));assert.equal(calculate({...s,price:1000},'shopee',{...cc,manual:true,percentage:20,perUnit:650,logisticRate:0},officialRules).fees,850);});
test('Shopee: preço ideal mínimo exato inclusive tarifa variável e saltos de faixa',()=>{for(const cost of [1,200,500,6000,8000,17000]){const ss={...s,cost,packaging:0,quantity:3};for(const target of [0,30]){let expected:number|null=null;for(let p=1;p<50000;p++){const r=calculate({...ss,price:p},'shopee',sc,officialRules);if(BigInt(r.profit)*10000n>=BigInt(r.revenue)*BigInt(target*100)){expected=p;break;}}assert.equal(calculateTargetPrice(ss,'shopee',sc,officialRules,target),expected);}}});
